# Generated by Django 5.1 on 2024-10-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplan",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="target_muscles",
            field=models.CharField(
                choices=[
                    ("back", "Back"),
                    ("chest", "Chest"),
                    ("biceps", "Biceps"),
                    ("triceps", "Triceps"),
                    ("legs", "Legs"),
                    ("shoulders", "Shoulders"),
                    ("core", "Core"),
                ],
                max_length=20,
            ),
        ),
    ]
