# Generated by Django 5.1 on 2024-10-29 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "welcome",
            "0003_remove_progress_exercise_workoutplan_calories_burned_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MuscleGroupExercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("back_exercises", models.IntegerField(default=0)),
                ("chest_exercises", models.IntegerField(default=0)),
                ("biceps_exercises", models.IntegerField(default=0)),
                ("triceps_exercises", models.IntegerField(default=0)),
                ("legs_exercises", models.IntegerField(default=0)),
                ("shoulders_exercises", models.IntegerField(default=0)),
                ("core_exercises", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
