# Generated by Django 5.1 on 2024-12-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0005_workoutplan_unique_user_workout_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplan",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
