# Generated by Django 5.1 on 2024-12-04 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0006_alter_workoutplan_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workoutplan",
            index=models.Index(
                fields=["user", "target_muscles"], name="user_target_muscle_idx"
            ),
        ),
    ]
